# Generated by Django 5.2.10 on 2026-02-19 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_image',
            field=models.ImageField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_undertaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='device_broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='device_condition_on_return',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Device condition when returned', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Admin Approval'), ('active', 'Active'), ('pending_return', 'Pending Return Approval'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='pending_approval', max_length=30),
        ),
    ]
